const PDFDocument = require('pdfkit');

/**
 * Builds the Document Checklist PDF for an application — page 2 of the
 * Master Application Pack (section 25). Lists every document the applicant
 * uploaded, plus what's still missing against the visa's mandatory list.
 *
 * @param {Object} app — populated Application doc (visaId, userId)
 * @param {Array}  requiredDocs — [{ documentName, required, critical }] from
 *                                 the matching VisaRule, or [] if none exists yet
 * @returns {Promise<Buffer>}
 */
function buildChecklistPDF(app, requiredDocs = []) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const W = doc.page.width;
    const uploadedTypes = new Set((app.documents || []).map(d => d.docType));

    doc.rect(0, 0, W, 80).fill('#0B3C5D');
    doc.fillColor('white').font('Helvetica-Bold').fontSize(22).text('VISAYATRI', 50, 20);
    doc.font('Helvetica').fontSize(11).fillColor('#90CAF9').text('Document Checklist', 50, 48);
    doc.fillColor('#FF7A00').fontSize(9).text(`Application #${app.applicationId}`, 50, 62);

    doc.moveDown(4);

    doc.fillColor('#0B3C5D').font('Helvetica-Bold').fontSize(13).text('Uploaded Documents');
    doc.moveDown(0.5);
    if (!app.documents?.length) {
      doc.font('Helvetica').fontSize(10).fillColor('#999').text('No documents uploaded yet.');
    } else {
      app.documents.forEach(d => {
        doc.font('Helvetica').fontSize(10).fillColor('#333')
          .text(`✓  ${d.docType}  —  ${d.originalName}  (${(d.size / 1024).toFixed(0)} KB)`, { indent: 10 });
      });
    }

    if (requiredDocs.length > 0) {
      doc.moveDown(1.5);
      doc.fillColor('#0B3C5D').font('Helvetica-Bold').fontSize(13).text('Official Requirements (from verified visa rule)');
      doc.moveDown(0.5);
      requiredDocs.forEach(rd => {
        const star = rd.critical ? '⭐ ' : '';
        doc.font('Helvetica').fontSize(10).fillColor(rd.required ? '#333' : '#888')
          .text(`${star}${rd.documentName}${rd.required ? '' : ' (optional)'}${rd.conditional ? ' — conditional: ' + (rd.condition || '') : ''}`, { indent: 10 });
      });
    }

    doc.moveDown(2);
    doc.fillColor('#999').font('Helvetica').fontSize(8)
      .text('Generated by Visayatri — this checklist reflects the state of the application at the time of generation.', { align: 'center' });

    doc.end();
  });
}

module.exports = { buildChecklistPDF };
